export enum ActivityType {
  CREATING = "CREATION",
  UPDATING = "UPDATE",
  LOGIN = "LOGIN",
  DELETING = "DELETING",
  RESET_PASSWORD = "RESET_PASSWORD",
  CHECKOUT = "CHECKOUT",
  CHECKOUT_ON_SINGLE_PRODUCT = "CHECKOUT",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  REGISTER = "REGISTER",
  ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
  CLEAR_CART = "CLEAR_CART",
  REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART",
}
